sudo: required
language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libedit-dev

stages:
  - test
  - install

jobs:
  include:
    - stage: test
      name: Tests
      install: skip
      script:
        - make test-mpc
      script:
        - make test-lexy

    - stage: install
      name: Install and Run
      before_install:
        - make
      install:
        - make install
      script:
        - lexy -v
        - lexy -r
        - lexy -e "(print (add 1 1))"
