language: c


matrix:
  include:
    # osx machines (x86-64)
    - os: osx
      osx_image: xcode12

    - os: osx
      osx_image: xcode11.3

    - os: osx
      osx_image: xcode10.1

    # linux machines (x86-64)
    - os: linux
      dist: Focal
      addons:
        apt:
          packages:
            - libedit-dev

    - os: linux
      dist: Bionic
      addons:
        apt:
          packages:
            - libedit-dev

    - os: linux
      dist: Xenial
      addons:
        apt:
          packages:
            - libedit-dev

    # linux machines (other archs)
    - os: linux
      dist: Focal
      arch: arm64
      addons:
        apt:
          packages:
            - libedit-dev

    - os: linux
      dist: Focal
      arch: ppc64le
      addons:
        apt:
          packages:
            - libedit-dev

    - os: linux
      dist: Focal
      arch: s390x
      addons:
        apt:
          packages:
            - libedit-dev


before_install:
  - time make test

install:
  - time make

script:
  - ./lexy -h
  - ./lexy -v
  - ./lexy -r
  - ./lexy examples/hello-world
  - ./lexy -e '(print (add 1 1))'
  - ./lexy -e '(use "lib/std") (print (nth-of {"a" "b" "c" "d" "e"} 2))'
