language: c


matrix:
  include:
    - os: linux
      dist: Focal
      addons:
        apt:
          packages:
            - libedit-dev

    - os: linux
      dist: Bionic
      addons:
        apt:
          packages:
            - libedit-dev

    - os: linux
      dist: Xenial
      addons:
        apt:
          packages:
            - libedit-dev

    - os: osx
      osx_image: xcode12

    - os: osx
      osx_image: xcode11.3

    - os: osx
      osx_image: xcode10.1


before_install:
  - make test

install:
  - make

script:
  - ./lexy -v
  - ./lexy -r
  - ./lexy -e '(print (add 1 1))'
  - ./lexy -e '(use "lib/std") (print (nth-of {"a" "b" "c" "d" "e"} 2))'
